### PR TITLE
create re-useable openshift templates for creating resoruces that uses DeploymentConfig and Secret rather then Pod and clear text password

### PR DESCRIPTION
**Pull request by itewk**
This patch does a few things.

* organizes folder structure
* adds templates for creating OpenShift resources using DeploymentConfig and Secret
* updates the readme

### CODE REVIEW

**Comment by itewk** [comment]
@tenortim I tested this with the latest isilon simulator with OCP v3.11.154

**Comment by itewk** [comment]
force pushes were doc updates and making the image name a parameter for those who need to build the image locally.

**Comment by itewk** [comment]
@tenortim are you still maintaining this or should I fork off and maintain my own?

**Comment by tenortim** [comment]
Hi @itewk,
apologies for the radio silence, have been a bit busy and not paying attention. Will look to review and merge shortly. Thanks for working on this!

**Comment by itewk** [comment]
@tenortim all good. Just wanted to be sure this was something you were still doing. Thanks for the time.

**Comment by itewk** [comment]
@tenortim wondering if this is still in your queue to review.

**Comment by itewk** [comment]
friendly ping :)

**Comment by itewk** [comment]
friendly ping :-D

**Comment by itewk** [comment]
Pong.

**Comment by itewk** [comment]
Friendly ping.

**Comment by itewk** [comment]
ping

**Pull request closed without merging**
